### ISSUE TITLE
Very odd biome generation behavior

### ISSUE THREAD

**Issue by nanakisan** [BrainSlugs83/NewBiospheresMod#34] opened 2015-05-05 07:59 UTC
This might come as incredibly strange. However the mod seems to cause biome placement in the oddest manner. It appears to cause biomes to generate in a perlin noise pattern and seems like it's a grid of sorts. Very peculiar behavior, is this a debug feature? Otherwise one would expect each sphere to generate as it's respective biome with a circle shaped biome assignment after generation. I only noticed this cause of the weird patching of biome colors in the spheres.

**Comment by Borkmeir** [comment] 2015-05-06 15:48
I think this is just the way the mod was originally written.  I remember the original Biospheres mod back in 1.2.5 did something similar.  However I agree that it is strange, and kind of problematic if playing with some other mods.  Back when this mod originated, biomes themselves were not very important, and most people were just looking for a particular type of terrain, so what biome it actually was didn't matter, but now that is not the case.  There are now a number of mods that have biome specific generation and mechanics, heck even vanilla has a little.  So it may be more important to handle biomes properly now, otherwise it might break gameplay.

Another strange biome behavior, is that it uses every biome from every mod installed, regardless of where that biome natively belongs, so you can find Nether biomes in the Overworld for example.  It also does not respect the basic materials of many biomes for the most part, which results in a sphere that is made up of Taiga Hills, and Birch Forest, that by terrain, appears to be a Desert.

I think it might be better for Biospheres to respect the terrain generation of all biomes present, instead of overriding everything with its own, and then add back the features you want from the original mod as decorators.  That may be difficult, to impossible though.  Also, it would be good if each sphere could be a distinct biome rather than a strange mix of two, or at the least a more natural split of biomes rather than trying to blend them with a noise pattern.

Ideally, what I would like to see, is the terrain generation of the original biomes, encapsulated at varying heights; the ability for other mods to add their structures and features through standard interfaces; Biospheres respecting what dimension the biome normally belongs in, and whether or not it is enabled; having the ability to disable ore generation, so I can control it with another mod if desired; and even the ability to enable/disable the terrain features of Biospheres, if needed.  

I realize some of this may already be possible in the current version.  I just wanted to describe what I'm envisioning overall.

**Comment by BrainSlugs83** [comment] 2015-05-11 01:40
@nanakisan, I believe what you describe is a dupe of #8, #13, #14, and #24.  It's currently fixed and will show up in the next release.

@Borkmeir, I agree! -- I believe this request is a dupe of #4, #5, and #6 -- the original terrain generation for this mod is very hackish, and it needs to invoke the biomes so that they do the world building instead of just having it do the world building on it's own.

For now I'm going to close this as a duplicate, if you think that's wrong, let me know and we can re-open it.  Thanks, guys. :-)

**Closed by BrainSlugs83** 2015-05-11 01:40 UTC
